chaoss/grimoirelab-core

.github/workflows/release.yml, .github/workflows/tests.yml, README.md, docker/Dockerfile, poetry.lock, pyproject.toml
Most recent Linux distributions provide Python 3.11 or 3.12 as the default version. Versions 3.8 and 3.9 are reaching their end of life soon, so we think it's better to drop these old versions and start fresh.
=> Set Python version to 3.11+

src/grimoirelab/core/scheduler/jobs.py, tests/scheduler/test_jobs.py
The PR fixes two errors that we found in the job loggers:
- The log was overwritten when multiple instances of the same job were instantiated
- Exceptions weren't logged
=> Fix job logger issues

src/grimoirelab/core/scheduler/tasks/chronicler.py, tests/scheduler/test_task_eventizer.py
This bug raise when the job was re-scheduled. The progress object stores the dates as 'YYYY-MM-DD' strings but the scheduler was trying to convert unix time dates to datetime.
=> Fix date parsing error when re-scheduling

poetry.lock, pyproject.toml, src/grimoirelab/core/config/settings.py, src/grimoirelab/core/scheduler/api.py, src/grimoirelab/core/scheduler/urls.py, src/grimoirelab/core/scheduler/worker.py
The new endpoints allows to get the list of tasks and jobs scheduled on the platform.
To implement this, we have added Django REST Framework library which provides nice stuff to add pagination, serialization, and others easily.
Django CORS Headers library was also added to deal with CORS issues.
The endpoints are:
- `/scheduler/tasks`: list of tasks
- `/scheduler/tasks/<uuid>/`: details of the requested task
- `/scheduler/tasks/<task_uuid>/jobs/`: jobs of the requested task
- `/scheduler/tasks/<task_uuid>/jobs/<uuid>/`: details of the requested job
- `/scheduler/tasks/<task_uuid>/jobs/<uuid>/logs/`: logs of the requested job
=> [scheduler:api] Add endpoint to get list of tasks and related info

src/grimoirelab/core/scheduler/api.py, src/grimoirelab/core/scheduler/views.py
This PR introduces two changes in the API:
- Parameters `backend` and `category` have been renamed to 'datasource_type' and `datasource_category` on `add_task`  endpoint.
- Data returned by the task list includes the new field `last_jobs`, which includes the data of the last 10 jobs run by a task.
=> Update task api

src/grimoirelab/core/scheduler/tasks/chronicler.py
In the case a worker dies while running an eventizer job, when recovering and re-scheduling the job the parameters are set as if the job ended successfully.
=> [scheduler:eventizer] Fix git recovery params when workers die

src/grimoirelab/core/runner/commands/run.py, src/grimoirelab/core/scheduler/db.py, src/grimoirelab/core/scheduler/scheduler.py, tests/scheduler/test_db.py, tests/scheduler/test_scheduler.py
When the server starts running, it will check first the state of the tasks, fixing any problem found.
=> Add function for task maintenance 

.github/workflows/changelog.yml, .github/workflows/docker-image.yml, .github/workflows/release.yml
Update files to support the migration of GrimoireLab repositories as part of the default branch transition from master to main.
=> Migrate files for branch rename from master to main

poetry.lock, pyproject.toml
Chronicler was previously included as a URL dependency due to the absence of a package. Now that a package is available, update the dependency to the latest version.
=> Update chronicler package dependency

poetry.lock, pyproject.toml
Chronicler was previously included as a package dependency, but we decided to set it as a Git dependency because we are not currently releasing packages.
=> Include Chronicler as Git dependency

src/grimoirelab/core/scheduler/scheduler.py, tests/scheduler/test_scheduler.py
Tasks were incorrectly rescheduled during the maintenance phase. The code was taking the data from the first task's job and not from the last one. This caused the task to run from the very beginning, again.
=> [scheduler] Fix re-scheduling tasks bug during maintenance

.flake8, .gitignore, pyproject.toml, scripts/build-ui.py
The UI is now built when either `poetry install` or `poetry build` are called. This ensures that the UI will be distributed and installed without extra steps.
This is critical when this git repository is installed as dependency. Previously, only the Python code was installed.
This commit also modifies the `.gitignore` file to make sure that only the UI code is distributed within the source package.
Fixes #26
=> [dist] Build UI when the package is installed/built

poetry.lock, pyproject.toml, src/grimoirelab/core/app/urls.py, src/grimoirelab/core/config/settings.py, src/grimoirelab/core/datasources/views.py, src/grimoirelab/core/permissions.py, src/grimoirelab/core/runner/commands/admin.py, src/grimoirelab/core/scheduler/views.py, src/grimoirelab/core/views.py, tests/datasources/test_views.py, ui/index.html
This PR integrates `djangorestframework-simplejwt` and includes two new endpoints for JWT token management: `/token/` for creating tokens and `/token/refresh/` for refreshing tokens. Additionally, it includes a new endpoint `/login/` that enables session login with CSRF token requirements.
GrimoireLab Core can work without authentication by setting `GRIMOIRELAB_AUTHENTICATION_REQUIRED` to `False`, which is intended for debugging purposes.
Fixes https://github.com/chaoss/grimoirelab-core/issues/30
=> [auth] Add JWT and Session Authentication

src/grimoirelab/core/scheduler/api.py, ui/src/components/JobList.vue, ui/src/components/OrderSelector.vue, ui/src/components/StatusIcon.vue, ui/src/components/TaskCard.vue, ui/src/components/TaskList/TaskList.vue, ui/src/components/TaskList/TaskListItem.vue, ui/src/composables/loading.js, ui/src/services/api/index.js, ui/src/stories/JobList.stories.js, ui/src/stories/OrderSelector.stories.js, ui/src/stories/StatusIcon.stories.js, ui/src/stories/TaskList.stories.js, ui/src/views/Job/ListView.vue, ui/src/views/Task/DetailView.vue, ui/src/views/Task/ListView.vue, ui/yarn.lock
This PR adds the option to filter the list of tasks and jobs by status, both on the API and the UI. The task list is ordered by latest run by default, with currently running tasks first.
It also adds some small improvements to the UI:
- Adds a spinner if the tasks or jobs are loading.
- Shows the last 10 jobs run in order and indicates if there are more than those 10 runs.
- The icon next to the last run info shows its status instead of the status of the task (which is usually 'enqueued').
- Shows the number of failures of the task if there have been any.
=> Order and filter tasks and jobs

src/grimoirelab/core/scheduler/scheduler.py, src/grimoirelab/core/scheduler/tasks/models.py
This PR fixes two scenarios where the scheduler could fail
- If a worker is forcibly stopped, the job may remain in the STARTED status. This update adds a check for expired jobs by comparing the job's expiration date with the current time when the status is STARTED and no heartbeat is detected.
- Before generating recovery arguments, this change verifies job progress. If progress is unavailable, it defaults to the initial arguments. It also generates initial arguments from the task when the task status is neither RECOVERY nor COMPLETED.
=> Handle scheduler corner cases of execution

src/grimoirelab/core/scheduler/scheduler.py, src/grimoirelab/core/scheduler/urls.py, src/grimoirelab/core/scheduler/views.py, tests/scheduler/test_scheduler.py
This PR introduces two new endpoints to manage tasks through both the API and the UI. You can now reschedule a failed task to run immediately or remove a task from the registry to stop its analysis.
Additionally, this commit fixes edge cases where tasks could become stuck in an inconsistent state.
=> [api] Add remove_task and reschedule_task to the API

src/grimoirelab/core/scheduler/tasks/models.py
This change adds a check for job progress before generating the resuming arguments. If progress is not available, it defaults to the initial arguments, as the resuming arguments can't be obtained from the job result.
=> [scheduler] Fix missing job progress on job completion

ui/src/services/api/client.js
This PR sets the default API base URL to `http://localhost:8000` only in development mode and `/`  in every other case. By default `yarn serve` runs in development mode and `yarn build` runs in production mode.
The base URL can be changed with the `VITE_API_ENDPOINT` env variable.
=> [ui] Remove default value for base API URL

src/grimoirelab/core/scheduler/scheduler.py
The connection may be closed after long-running tasks. This could happen if the database restarts or reaches the connection timeout without being used.
This PR closes unusable connections before using them and lets Django reopen them if needed.
This is related to https://github.com/chaoss/grimoirelab/issues/751 but has not been tested in production to know if it fixes the error.
=> [job] Check database connection after job execution

src/grimoirelab/core/scheduler/api.py, ui/src/components/TaskList/TaskList.vue
The `status` filter is not very useful when searching for failed tasks since tasks rarely have that status. This PR changes the `status` filter in the eventizer task list endpoint to return all tasks that have failed at some point in their run history when filtering for failed tasks. It also adds a `last_run_status` filter and a tab in the UI to show tasks that have failed in their last execution.
=> Improve failed tasks filter

ui/src/views/Job/ListView.vue, ui/src/views/Task/DetailView.vue
Reloads a task's list of jobs when the task data changes, eg. when it is rescheduled or canceled.
=> [ui] Reload task jobs when task changes

.github/workflows/tests.yml
The jobs of the test workflow only need the minimum permissions to run. In this case, we limit the scope to the minimal starting point that is 'read' privileges for 'content' access. All other scopes ('issues', 'pull-requests', etc) are set to 'none' when they aren't defined.
=> [ci] Add permissions to the test workflow

.pre-commit-config.yaml
This makes the use of hooks more secure, avoiding tampering of git tags versions.
=> Update pre-commit hooks to use sha refs instead of tags

ui/src/components/EcosystemSelector.vue
This PR fixes an issue with the ecosystem name disappearing from the top bar when it is selected twice.
Fixes #88
=> [ui] Fix ecosystem name dissapearing

src/grimoirelab/core/config/settings.py, src/grimoirelab/core/consumers/archivist.py, src/grimoirelab/core/consumers/consumer_pool.py, src/grimoirelab/core/runner/commands/run.py, tests/integration/conftest.py, tests/integration/test_archivist.py, tests/unit/consumers/test_archivist.py, tests/unit/consumers/test_consumer_pool.py
Previously, all events were stored in a single index, which reduced performance in OpenSearch as the index grew too large.
This change introduces support for defining a rollover policy in the Archivist configuration. The policy allows indices to roll over automatically once they reach a specified size, improving search and indexing performance in OpenSearch.
Rollover is now the default behavior, but inserting into a single index remains supported if explicitly configured.
New environment variables with their default values are:
- GRIMOIRELAB_ARCHIVIST_ROLLOVER_INDICES = True
- GRIMOIRELAB_ARCHIVIST_ROLLOVER_SIZE = 20gb
=> Add rollover index to archivist settings

src/grimoirelab/core/runner/commands/run.py, src/grimoirelab/core/scheduler/scheduler.py
Server, producer and consumers wait until the required services are up before starting.
Fixes https://github.com/chaoss/grimoirelab/issues/740
=> [cmd] Check services are up when the platform starts

src/grimoirelab/core/consumers/consumer.py, src/grimoirelab/core/scheduler/tasks/chronicler.py, tests/integration/test_archivist.py
Use a Redis pipeline to batch commands for adding events. This improves performance by reducing the number of round trips to the Redis server, especially when processing a large number of events.
This PR also fixes a bug. When pending entries existed in Redis but hadn't reached the minimum idle time, XAUTOCLAIM didn't return '0-0' as the next ID. Instead, it returned a different ID, causing the consumer to remain stuck until all recovered entries were processed, blocking new entries from being handled.
Fixes https://github.com/chaoss/grimoirelab/issues/760
=> Optimize event processing with pipeline and fix a bug
